* fzf-tools-launcher
Browse & preview file contents, and launch tools/pipelines to process the chosen files.
** Installation & requirements
This file needs to be sourced into your zsh shell (e.g. in your init file),
and tmux needs to be running before you can use it.
** Usage & description
> fzf-tool-launcher [FILE..]
   
This function allows you to browse files (passed as args) using fzf,
and then launch a tool (e.g. fzfrepl) to process the data in the file.
As you navigate the files menu, the preview window will display the
file contents using a predefined command to format the output.
A different command is used for each different file-ending, and large
files are truncated before displaying unformatted (so it's fast).
At the top of the preview window the file size, ownership & permissions
are displayed, and the word "FORMATTED", or "RAW" for large truncated files.

When you select a file by pressing enter, you will be presented with a
menu of tool names. At the bottom of this menu the command line corresponding
to the tool is displayed. Pressing enter in the menu will open a new tmux window
to run the tool on the file. The old window will stay open; press Ctrl+g
to return to the file menu.
** Configuration
Preview commands and other options are stored as zstyles, and the tools
menu items are stored in a config file. To set a preview command for a
particular file-ending, use the file-ending as the style name, and
':fzf-tools-launcher:previewcmd:' as the context, e.g:

zstyle ':fzf-tools-launcher:previewcmd:' csv 'mlr --icsv --opprint cat {}'

{} is a placeholder for the filename.

By default the tools menu is defined in ~/.fzfrepl/tools_menu, but you
can change this location by setting the toolsmenu style, like this:

zstyle ':fzf-tools-launcher:' toolsmenu "~/.fzfrepl/tools_menu"

Each line of that file can either be a comment line starting with #,
or a tool definition; a word naming the tool, followed by the command,
e.g:

mlr_repl fzfrepl.sh -o -c "mlr {q}" -q "cat" {}

(again {} is a placeholder for the filename).

As mentioned earlier, large files are truncated before displaying in
the preview window unformatted. The default threshold for what counts
as a large file is 10485760 bytes (10MiB), but you can change it like
this:

zstyle ':fzf-tools-launcher:' max_preview_size 5242880

** Keybindings
*** File menu
| Alt+v  | view entire formatted file with $PAGER (unless its larger than max_preview_size) |
| Ctrl+v | view entire raw file with $PAGER                                                 |
| Ctrl+j | exit and print the selected file                                                 |
*** Tools menu
| Enter | run the selected tool on the selected file |
** Copyright notice
Copyright (C) 2021 Joe Bloggs vapniks@yahoo.com

This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with this program. If not, see http://www.gnu.org/licenses/.   
